name: fast-record
version: 0.0.1
category: Data
synopsis: Fast anonymous records.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/fast-record

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - integer-gmp
  - microlens

library:
  source-dirs: src
